# Configuration file of Kuiper training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU)
ps_ip: 10.0.0.2

# ip address of each worker:# of gpus on this worker
# Note that if we collocate ps and worker, then we need to decrease this number of gpus by 1
# E.g., master node has 4 GPUs, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    - 10.0.0.3:[2] # worker_ip: # of gpus
    - 10.0.0.4:[2] 
    - 10.0.0.5:[2]
    - 10.0.0.6:[2]
    - 10.0.0.7:[2]
    - 10.0.0.8:[2]
    - 10.0.0.9:[2]
    - 10.0.0.10:[2]
    - 10.0.0.11:[2]
    - 10.0.0.12:[2]
    - 10.0.0.13:[2]
      #- 10.0.0.14:[2]

exp_path: $HOME/FLPerf-Private/training

# Entry function of executor and aggregator under $exp_path
executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run kuiper (in order)
setup_commands:
    - source $HOME/anaconda3/bin/activate kuiper    
    - export NCCL_SOCKET_IFNAME='enp94s0f0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - log_path: $HOME/FLPerf-Private/training/evals # Path of log files
    - job_name: reddit                   # Generate logs under this folder: log_path/job_name/time_stamp
    - total_worker: 100                     # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: blog                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: $HOME/FLPerf/reddit    # Path of the dataset
    #- data_map_file: $HOME/FLPerf/reddit/client_data_mapping/train.csv              # Allocation of data to each client, turn to iid setting if not provided
    #- device_conf_file: $HOME/FLPerf/data/device_info/client_device_capacity     # Path of the client trace
    #- device_avail_file: $HOME/FLPerf/data/device_info/client_behave_trace
    - model: mobilebert                            # Models: shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
      #- gradient_policy: yogi                 # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - eval_interval: 30                     # How many rounds to run a testing on the testing set
    - epochs: 5000                          # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - num_loaders: 4
    - batch_size: 16
    - local_steps: 20
    - test_bsz: 16
    - task: nlp
    - test_ratio: 0.2
    - learning_rate: 4e-5
    - min_learning_rate: 1e-5
    - decay_epoch: 10
